# Generated by Django 4.2.6 on 2023-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='promo id')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='vacancy')),
                ('info', models.TextField(blank=True, max_length=1024, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
