# Generated by Django 4.2.6 on 2023-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='promo id')),
                ('question', models.CharField(max_length=16, unique=True)),
                ('answer', models.TextField(max_length=1024)),
            ],
        ),
    ]
