# Generated by Django 4.2.6 on 2023-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='article id')),
                ('header', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField(max_length=8192)),
                ('image', models.ImageField(upload_to='about/models/articles')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date and time')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
