# Generated by Django 4.2.6 on 2023-12-13 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='promo id')),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2000000)])),
            ],
            options={
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
