# Generated by Django 4.2.6 on 2023-10-18 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.order'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Part name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='parttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parttype', verbose_name='Part type'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Price'),
        ),
    ]
