# Generated by Django 4.2.6 on 2023-10-18 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='review',
            name='header',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
