# Generated by Django 4.2.6 on 2023-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_order_datetime_alter_review_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='info',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Additional info'),
        ),
    ]
