# Generated by Django 4.2.6 on 2023-10-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_order_info_alter_part_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='master',
            name='name',
        ),
    ]
