# Generated by Django 4.2.6 on 2023-10-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['name']},
        ),
    ]
