# Generated by Django 4.2.6 on 2023-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='promo id')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='promo code')),
                ('info', models.CharField(max_length=1024, verbose_name='description')),
                ('code_apply', models.CharField(editable=False, max_length=8192)),
                ('code_check', models.CharField(editable=False, max_length=8192)),
            ],
        ),
    ]
