# Generated by Django 4.2.6 on 2023-10-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='code_apply',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='code_check',
        ),
    ]
