# Generated by Django 4.2.6 on 2023-10-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_promo_code_apply_remove_promo_code_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='info',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='description'),
        ),
    ]
