# Generated by Django 4.2.6 on 2023-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_promo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='info',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='description'),
        ),
    ]
