# Generated by Django 4.2.6 on 2023-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
