# Generated by Django 4.2.6 on 2023-10-17 14:48

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.ForeignKey(default=authentication.models.User.timezone_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.timezone'),
        ),
    ]
